/*
 * Rune glyphs, generated by tools/build-glyphs.js from the labelled
 * alphabet charts in fonts/. Do not edit by hand — rerun the tool.
 *
 * Each font is one horizontal strip of white-on-transparent runes; the
 * map gives each character its offset and width within that strip.
 */
(function (global) {
  'use strict';

  global.Glyphs = {
    "minecraft:alt": {
      "sheet": "assets/fonts/sga.png",
      "width": 505,
      "height": 27,
      "glyphs": {
        "a": {
          "x": 0,
          "w": 21
        },
        "b": {
          "x": 22,
          "w": 26
        },
        "c": {
          "x": 49,
          "w": 6
        },
        "d": {
          "x": 56,
          "w": 25
        },
        "e": {
          "x": 82,
          "w": 24
        },
        "f": {
          "x": 107,
          "w": 25
        },
        "g": {
          "x": 133,
          "w": 9
        },
        "h": {
          "x": 143,
          "w": 24
        },
        "i": {
          "x": 168,
          "w": 5
        },
        "j": {
          "x": 174,
          "w": 4
        },
        "k": {
          "x": 179,
          "w": 18
        },
        "l": {
          "x": 198,
          "w": 13
        },
        "m": {
          "x": 212,
          "w": 24
        },
        "n": {
          "x": 237,
          "w": 15
        },
        "o": {
          "x": 253,
          "w": 15
        },
        "p": {
          "x": 269,
          "w": 15
        },
        "q": {
          "x": 285,
          "w": 24
        },
        "r": {
          "x": 310,
          "w": 24
        },
        "s": {
          "x": 335,
          "w": 15
        },
        "t": {
          "x": 351,
          "w": 20
        },
        "u": {
          "x": 372,
          "w": 24
        },
        "v": {
          "x": 397,
          "w": 25
        },
        "w": {
          "x": 423,
          "w": 24
        },
        "x": {
          "x": 448,
          "w": 20
        },
        "y": {
          "x": 469,
          "w": 15
        },
        "z": {
          "x": 485,
          "w": 20
        }
      }
    },
    "minecraft:illageralt": {
      "sheet": "assets/fonts/illageralt.png",
      "width": 407,
      "height": 17,
      "glyphs": {
        "1": {
          "x": 311,
          "w": 7
        },
        "2": {
          "x": 319,
          "w": 7
        },
        "3": {
          "x": 327,
          "w": 7
        },
        "4": {
          "x": 335,
          "w": 7
        },
        "5": {
          "x": 343,
          "w": 11
        },
        "6": {
          "x": 355,
          "w": 7
        },
        "7": {
          "x": 363,
          "w": 7
        },
        "8": {
          "x": 371,
          "w": 7
        },
        "9": {
          "x": 379,
          "w": 7
        },
        "a": {
          "x": 0,
          "w": 11
        },
        "b": {
          "x": 12,
          "w": 11
        },
        "c": {
          "x": 24,
          "w": 11
        },
        "d": {
          "x": 36,
          "w": 11
        },
        "e": {
          "x": 48,
          "w": 11
        },
        "f": {
          "x": 60,
          "w": 11
        },
        "g": {
          "x": 72,
          "w": 14
        },
        "h": {
          "x": 87,
          "w": 11
        },
        "i": {
          "x": 99,
          "w": 11
        },
        "j": {
          "x": 111,
          "w": 11
        },
        "k": {
          "x": 123,
          "w": 11
        },
        "l": {
          "x": 135,
          "w": 11
        },
        "m": {
          "x": 147,
          "w": 11
        },
        "n": {
          "x": 159,
          "w": 11
        },
        "o": {
          "x": 171,
          "w": 11
        },
        "p": {
          "x": 183,
          "w": 9
        },
        "q": {
          "x": 193,
          "w": 11
        },
        "r": {
          "x": 205,
          "w": 11
        },
        "s": {
          "x": 217,
          "w": 11
        },
        "t": {
          "x": 229,
          "w": 11
        },
        "u": {
          "x": 241,
          "w": 11
        },
        "v": {
          "x": 253,
          "w": 11
        },
        "w": {
          "x": 265,
          "w": 11
        },
        "x": {
          "x": 277,
          "w": 9
        },
        "y": {
          "x": 287,
          "w": 11
        },
        "z": {
          "x": 299,
          "w": 11
        },
        "?": {
          "x": 387,
          "w": 5
        },
        "!": {
          "x": 393,
          "w": 5
        },
        ".": {
          "x": 399,
          "w": 2
        },
        ",": {
          "x": 402,
          "w": 5
        }
      }
    }
  };
})(window);
